import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Table from '../components/Table'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <DataTable></DataTable>
      </main>
    </div>
  )
}

function DataTable() {
  const [state, setState] = useState([])

  useEffect(() => {
    fetch('/api/books?sort=title')
      .then(res => res.json())
      .then(setState)
  }, [])
  return <Table 
            headers={[
              {label: "ID", column: "book_id"}, 
              {label: "Name", column: "title"}, 
              {label: "Genre", column: "genre"},
              {label: "Release Year", column: "releaseYear"}
            ]}
            body={state}
  ></Table>
}

export default Home
